In [3]:
a = np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [2]:
import numpy as np

In [4]:
a[1,5]

13

In [5]:
a[1,-2]

13

In [6]:
# Get a specific row
a[0,:]

array([1, 2, 3, 4, 5, 6, 7])

In [7]:
# Get a specific column 
a[:,2]

array([ 3, 10])

In [9]:
# Getting a little more fancy [startindex:endindex:stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [11]:
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [12]:
a[:,2]=[1,2]
print(a)

[[ 1  2  1  4  5  6  7]
 [ 8  9  2 11 12 20 14]]


In [16]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [17]:
# Get specific element (work outside in)
b[0,1,1]

4

In [18]:
# Initializing different type of arrays

In [20]:
# All Os matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [23]:
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]], dtype=int32)

In [25]:
# Any other number
np.full((2,2),99)

array([[99, 99],
       [99, 99]])

In [27]:
# Any other number (full_like)
np.full_like(a, 4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [28]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.77176942, 0.18095008],
       [0.28676333, 0.99676979],
       [0.62133037, 0.24014474],
       [0.79617947, 0.89430968]])

In [32]:
# Random Integer Values
np.random.randint(-7,8,size=(3,3))

array([[-6, -7,  3],
       [-5, -2, -5],
       [ 0, -6,  4]])

In [34]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [37]:
# Repeat an Array
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]
