In [1]:
import numpy as np

In [20]:
a=np.array([1,2,3],dtype='int32')

In [4]:
print(a)

[1 2 3]


In [6]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [12]:
# Get Dimension
a.ndim

1

In [11]:
b.shape

(2, 3)

In [21]:
# Get type
a.dtype

dtype('int32')

In [18]:
a.itemsize
# in bytes

2

In [19]:
# Get the total size
a.nbytes

6