In [1]:
import numpy as np

### Mathematics

In [3]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [4]:
a+2

array([3, 4, 5, 6])

In [11]:
b=np.array([1,1,1,2])
a+b

array([ 8,  9, 10, 12])

In [12]:
# Take the sin
np.sin(a)

array([ 0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

### Linear Algebra

In [13]:
# multiplying matrices

In [15]:
a= np.ones((2,3))
print(a)

[[1. 1. 1.]
 [1. 1. 1.]]


In [16]:
b=np.full((3,2),2)
print(b)

[[2 2]
 [2 2]
 [2 2]]


In [17]:
np.matmul(a,b)

array([[6., 6.],
       [6., 6.]])

In [18]:
# Find the determinant
c=np.identity(3)
np.linalg.det(c)

1.0

### Statistics

In [19]:
stats=np.array([[1,2,3],[4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
np.min(stats)

1

In [21]:
np.max(stats)

6

In [25]:
np.sum(stats,axis=0)

array([5, 7, 9])

In [26]:
a = np.array(([1, 2, 3, 4, 5], [6, 7, 8, 9, 10]))
print(a)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [28]:
b=np.max(a,axis=1).sum()
print(b)

15


### Reorganizing Arrays

In [33]:
before = np.array([[1,2,3,4],[5,6,7,8]])
print(before)

[[1 2 3 4]
 [5 6 7 8]]


In [36]:
after=before.reshape((4,2))
print(after)

[[1 2]
 [3 4]
 [5 6]
 [7 8]]


In [40]:
# Vertically stacking vectors

v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])


np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [44]:
# Horizontal stack

h1=np.ones((2,4))
h2=np.zeros((2,2))

np.hstack([h1,h2])

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])